version: 2
jobs:
  build:

    docker:
      - image: circleci/node:8.11.1
    working_directory: ~/Black-Belt-Eagle-Scout

    steps:
      - checkout

      # special step to restore the dependency cache
      - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'

      - run:
          name: install-npm
          command: npm install

      # special step to save the dependency cache
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run:
          name: Build Static Files
          command: npm run generate

      - run:
          name: Deploy to Surge
          command: npm run deploy
